FROM twlight_base

# Build dependencies.
RUN apk add --update \
    build-base \
    gcc \
    jpeg-dev zlib-dev \
    libxml2-dev libxslt-dev \
    musl-dev \
    python-dev

# Pip dependencies.
COPY requirements /requirements
RUN virtualenv /venv ;\
    source /venv/bin/activate ;\
    pip install -r /requirements/wmf.txt

VOLUME /venv
