# -*- coding: utf-8 -*-


from django.db import models, migrations
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Editor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        verbose_name="ID",
                        serialize=False,
                        auto_created=True,
                        primary_key=True,
                    ),
                ),
                (
                    "last_updated",
                    models.DateField(
                        help_text="When this information was last edited", auto_now=True
                    ),
                ),
                (
                    "account_created",
                    models.DateField(
                        help_text="When this information was first created",
                        auto_now_add=True,
                    ),
                ),
                ("wp_username", models.CharField(help_text="Username", max_length=235)),
                ("wp_editcount", models.IntegerField(help_text="Wikipedia edit count")),
                (
                    "wp_registered",
                    models.DateField(help_text="Date registered at Wikipedia"),
                ),
                ("wp_sub", models.IntegerField(help_text="Wikipedia user ID")),
                ("_wp_internal", models.TextField()),
                (
                    "home_wiki",
                    models.CharField(
                        help_text="Home wiki, as indicated by user",
                        max_length=4,
                        choices=[
                            (b"aa", b"aa.wikipedia.org/wiki/"),
                            (b"ab", b"ab.wikipedia.org/wiki/"),
                            (b"ace", b"ace.wikipedia.org/wiki/"),
                            (b"af", b"af.wikipedia.org/wiki/"),
                            (b"ak", b"ak.wikipedia.org/wiki/"),
                            (b"als", b"als.wikipedia.org/wiki/"),
                            (b"am", b"am.wikipedia.org/wiki/"),
                            (b"an", b"an.wikipedia.org/wiki/"),
                            (b"ang", b"ang.wikipedia.org/wiki/"),
                            (b"ar", b"ar.wikipedia.org/wiki/"),
                            (b"arc", b"arc.wikipedia.org/wiki/"),
                            (b"arz", b"arz.wikipedia.org/wiki/"),
                            (b"as", b"as.wikipedia.org/wiki/"),
                            (b"ast", b"ast.wikipedia.org/wiki/"),
                            (b"av", b"av.wikipedia.org/wiki/"),
                            (b"ay", b"ay.wikipedia.org/wiki/"),
                            (b"az", b"az.wikipedia.org/wiki/"),
                            (b"azb", b"azb.wikipedia.org/wiki/"),
                            (b"ba", b"ba.wikipedia.org/wiki/"),
                            (b"bar", b"bar.wikipedia.org/wiki/"),
                            (b"bat-smg", b"bat-smg.wikipedia.org/wiki/"),
                            (b"bcl", b"bcl.wikipedia.org/wiki/"),
                            (b"be", b"be.wikipedia.org/wiki/"),
                            (b"be-x-old", b"be-x-old.wikipedia.org/wiki/"),
                            (b"bg", b"bg.wikipedia.org/wiki/"),
                            (b"bh", b"bh.wikipedia.org/wiki/"),
                            (b"bi", b"bi.wikipedia.org/wiki/"),
                            (b"bjn", b"bjn.wikipedia.org/wiki/"),
                            (b"bm", b"bm.wikipedia.org/wiki/"),
                            (b"bn", b"bn.wikipedia.org/wiki/"),
                            (b"bo", b"bo.wikipedia.org/wiki/"),
                            (b"bpy", b"bpy.wikipedia.org/wiki/"),
                            (b"br", b"br.wikipedia.org/wiki/"),
                            (b"bs", b"bs.wikipedia.org/wiki/"),
                            (b"bug", b"bug.wikipedia.org/wiki/"),
                            (b"bxr", b"bxr.wikipedia.org/wiki/"),
                            (b"ca", b"ca.wikipedia.org/wiki/"),
                            (b"cbk-zam", b"cbk-zam.wikipedia.org/wiki/"),
                            (b"cdo", b"cdo.wikipedia.org/wiki/"),
                            (b"ce", b"ce.wikipedia.org/wiki/"),
                            (b"ceb", b"ceb.wikipedia.org/wiki/"),
                            (b"ch", b"ch.wikipedia.org/wiki/"),
                            (b"cho", b"cho.wikipedia.org/wiki/"),
                            (b"chr", b"chr.wikipedia.org/wiki/"),
                            (b"chy", b"chy.wikipedia.org/wiki/"),
                            (b"ckb", b"ckb.wikipedia.org/wiki/"),
                            (b"co", b"co.wikipedia.org/wiki/"),
                            (b"cr", b"cr.wikipedia.org/wiki/"),
                            (b"crh", b"crh.wikipedia.org/wiki/"),
                            (b"cs", b"cs.wikipedia.org/wiki/"),
                            (b"csb", b"csb.wikipedia.org/wiki/"),
                            (b"cu", b"cu.wikipedia.org/wiki/"),
                            (b"cv", b"cv.wikipedia.org/wiki/"),
                            (b"cy", b"cy.wikipedia.org/wiki/"),
                            (b"da", b"da.wikipedia.org/wiki/"),
                            (b"de", b"de.wikipedia.org/wiki/"),
                            (b"diq", b"diq.wikipedia.org/wiki/"),
                            (b"dsb", b"dsb.wikipedia.org/wiki/"),
                            (b"dv", b"dv.wikipedia.org/wiki/"),
                            (b"dz", b"dz.wikipedia.org/wiki/"),
                            (b"ee", b"ee.wikipedia.org/wiki/"),
                            (b"el", b"el.wikipedia.org/wiki/"),
                            (b"eml", b"eml.wikipedia.org/wiki/"),
                            (b"en", b"en.wikipedia.org/wiki/"),
                            (b"eo", b"eo.wikipedia.org/wiki/"),
                            (b"es", b"es.wikipedia.org/wiki/"),
                            (b"et", b"et.wikipedia.org/wiki/"),
                            (b"eu", b"eu.wikipedia.org/wiki/"),
                            (b"ext", b"ext.wikipedia.org/wiki/"),
                            (b"fa", b"fa.wikipedia.org/wiki/"),
                            (b"ff", b"ff.wikipedia.org/wiki/"),
                            (b"fi", b"fi.wikipedia.org/wiki/"),
                            (b"fiu-vro", b"fiu-vro.wikipedia.org/wiki/"),
                            (b"fj", b"fj.wikipedia.org/wiki/"),
                            (b"fo", b"fo.wikipedia.org/wiki/"),
                            (b"fr", b"fr.wikipedia.org/wiki/"),
                            (b"frp", b"frp.wikipedia.org/wiki/"),
                            (b"frr", b"frr.wikipedia.org/wiki/"),
                            (b"fur", b"fur.wikipedia.org/wiki/"),
                            (b"fy", b"fy.wikipedia.org/wiki/"),
                            (b"ga", b"ga.wikipedia.org/wiki/"),
                            (b"gag", b"gag.wikipedia.org/wiki/"),
                            (b"gan", b"gan.wikipedia.org/wiki/"),
                            (b"gd", b"gd.wikipedia.org/wiki/"),
                            (b"gl", b"gl.wikipedia.org/wiki/"),
                            (b"glk", b"glk.wikipedia.org/wiki/"),
                            (b"gn", b"gn.wikipedia.org/wiki/"),
                            (b"gom", b"gom.wikipedia.org/wiki/"),
                            (b"got", b"got.wikipedia.org/wiki/"),
                            (b"gu", b"gu.wikipedia.org/wiki/"),
                            (b"gv", b"gv.wikipedia.org/wiki/"),
                            (b"ha", b"ha.wikipedia.org/wiki/"),
                            (b"hak", b"hak.wikipedia.org/wiki/"),
                            (b"haw", b"haw.wikipedia.org/wiki/"),
                            (b"he", b"he.wikipedia.org/wiki/"),
                            (b"hi", b"hi.wikipedia.org/wiki/"),
                            (b"hif", b"hif.wikipedia.org/wiki/"),
                            (b"ho", b"ho.wikipedia.org/wiki/"),
                            (b"hr", b"hr.wikipedia.org/wiki/"),
                            (b"hsb", b"hsb.wikipedia.org/wiki/"),
                            (b"ht", b"ht.wikipedia.org/wiki/"),
                            (b"hu", b"hu.wikipedia.org/wiki/"),
                            (b"hy", b"hy.wikipedia.org/wiki/"),
                            (b"hz", b"hz.wikipedia.org/wiki/"),
                            (b"ia", b"ia.wikipedia.org/wiki/"),
                            (b"id", b"id.wikipedia.org/wiki/"),
                            (b"ie", b"ie.wikipedia.org/wiki/"),
                            (b"ig", b"ig.wikipedia.org/wiki/"),
                            (b"ii", b"ii.wikipedia.org/wiki/"),
                            (b"ik", b"ik.wikipedia.org/wiki/"),
                            (b"ilo", b"ilo.wikipedia.org/wiki/"),
                            (b"io", b"io.wikipedia.org/wiki/"),
                            (b"is", b"is.wikipedia.org/wiki/"),
                            (b"it", b"it.wikipedia.org/wiki/"),
                            (b"iu", b"iu.wikipedia.org/wiki/"),
                            (b"ja", b"ja.wikipedia.org/wiki/"),
                            (b"jbo", b"jbo.wikipedia.org/wiki/"),
                            (b"jv", b"jv.wikipedia.org/wiki/"),
                            (b"ka", b"ka.wikipedia.org/wiki/"),
                            (b"kaa", b"kaa.wikipedia.org/wiki/"),
                            (b"kab", b"kab.wikipedia.org/wiki/"),
                            (b"kbd", b"kbd.wikipedia.org/wiki/"),
                            (b"kg", b"kg.wikipedia.org/wiki/"),
                            (b"ki", b"ki.wikipedia.org/wiki/"),
                            (b"kj", b"kj.wikipedia.org/wiki/"),
                            (b"kk", b"kk.wikipedia.org/wiki/"),
                            (b"kl", b"kl.wikipedia.org/wiki/"),
                            (b"km", b"km.wikipedia.org/wiki/"),
                            (b"kn", b"kn.wikipedia.org/wiki/"),
                            (b"ko", b"ko.wikipedia.org/wiki/"),
                            (b"koi", b"koi.wikipedia.org/wiki/"),
                            (b"kr", b"kr.wikipedia.org/wiki/"),
                            (b"krc", b"krc.wikipedia.org/wiki/"),
                            (b"ks", b"ks.wikipedia.org/wiki/"),
                            (b"ksh", b"ksh.wikipedia.org/wiki/"),
                            (b"ku", b"ku.wikipedia.org/wiki/"),
                            (b"kv", b"kv.wikipedia.org/wiki/"),
                            (b"kw", b"kw.wikipedia.org/wiki/"),
                            (b"ky", b"ky.wikipedia.org/wiki/"),
                            (b"la", b"la.wikipedia.org/wiki/"),
                            (b"lad", b"lad.wikipedia.org/wiki/"),
                            (b"lb", b"lb.wikipedia.org/wiki/"),
                            (b"lbe", b"lbe.wikipedia.org/wiki/"),
                            (b"lez", b"lez.wikipedia.org/wiki/"),
                            (b"lg", b"lg.wikipedia.org/wiki/"),
                            (b"li", b"li.wikipedia.org/wiki/"),
                            (b"lij", b"lij.wikipedia.org/wiki/"),
                            (b"lmo", b"lmo.wikipedia.org/wiki/"),
                            (b"ln", b"ln.wikipedia.org/wiki/"),
                            (b"lo", b"lo.wikipedia.org/wiki/"),
                            (b"lrc", b"lrc.wikipedia.org/wiki/"),
                            (b"lt", b"lt.wikipedia.org/wiki/"),
                            (b"ltg", b"ltg.wikipedia.org/wiki/"),
                            (b"lv", b"lv.wikipedia.org/wiki/"),
                            (b"mai", b"mai.wikipedia.org/wiki/"),
                            (b"map-bms", b"map-bms.wikipedia.org/wiki/"),
                            (b"mdf", b"mdf.wikipedia.org/wiki/"),
                            (b"mg", b"mg.wikipedia.org/wiki/"),
                            (b"mh", b"mh.wikipedia.org/wiki/"),
                            (b"mhr", b"mhr.wikipedia.org/wiki/"),
                            (b"mi", b"mi.wikipedia.org/wiki/"),
                            (b"min", b"min.wikipedia.org/wiki/"),
                            (b"mk", b"mk.wikipedia.org/wiki/"),
                            (b"ml", b"ml.wikipedia.org/wiki/"),
                            (b"mn", b"mn.wikipedia.org/wiki/"),
                            (b"mo", b"mo.wikipedia.org/wiki/"),
                            (b"mr", b"mr.wikipedia.org/wiki/"),
                            (b"mrj", b"mrj.wikipedia.org/wiki/"),
                            (b"ms", b"ms.wikipedia.org/wiki/"),
                            (b"mt", b"mt.wikipedia.org/wiki/"),
                            (b"mus", b"mus.wikipedia.org/wiki/"),
                            (b"mwl", b"mwl.wikipedia.org/wiki/"),
                            (b"my", b"my.wikipedia.org/wiki/"),
                            (b"myv", b"myv.wikipedia.org/wiki/"),
                            (b"mzn", b"mzn.wikipedia.org/wiki/"),
                            (b"na", b"na.wikipedia.org/wiki/"),
                            (b"nah", b"nah.wikipedia.org/wiki/"),
                            (b"nap", b"nap.wikipedia.org/wiki/"),
                            (b"nds", b"nds.wikipedia.org/wiki/"),
                            (b"nds-nl", b"nds-nl.wikipedia.org/wiki/"),
                            (b"ne", b"ne.wikipedia.org/wiki/"),
                            (b"new", b"new.wikipedia.org/wiki/"),
                            (b"ng", b"ng.wikipedia.org/wiki/"),
                            (b"nl", b"nl.wikipedia.org/wiki/"),
                            (b"nn", b"nn.wikipedia.org/wiki/"),
                            (b"no", b"no.wikipedia.org/wiki/"),
                            (b"nov", b"nov.wikipedia.org/wiki/"),
                            (b"nrm", b"nrm.wikipedia.org/wiki/"),
                            (b"nso", b"nso.wikipedia.org/wiki/"),
                            (b"nv", b"nv.wikipedia.org/wiki/"),
                            (b"ny", b"ny.wikipedia.org/wiki/"),
                            (b"oc", b"oc.wikipedia.org/wiki/"),
                            (b"om", b"om.wikipedia.org/wiki/"),
                            (b"or", b"or.wikipedia.org/wiki/"),
                            (b"os", b"os.wikipedia.org/wiki/"),
                            (b"pa", b"pa.wikipedia.org/wiki/"),
                            (b"pag", b"pag.wikipedia.org/wiki/"),
                            (b"pam", b"pam.wikipedia.org/wiki/"),
                            (b"pap", b"pap.wikipedia.org/wiki/"),
                            (b"pcd", b"pcd.wikipedia.org/wiki/"),
                            (b"pdc", b"pdc.wikipedia.org/wiki/"),
                            (b"pfl", b"pfl.wikipedia.org/wiki/"),
                            (b"pi", b"pi.wikipedia.org/wiki/"),
                            (b"pih", b"pih.wikipedia.org/wiki/"),
                            (b"pl", b"pl.wikipedia.org/wiki/"),
                            (b"pms", b"pms.wikipedia.org/wiki/"),
                            (b"pnb", b"pnb.wikipedia.org/wiki/"),
                            (b"pnt", b"pnt.wikipedia.org/wiki/"),
                            (b"ps", b"ps.wikipedia.org/wiki/"),
                            (b"pt", b"pt.wikipedia.org/wiki/"),
                            (b"qu", b"qu.wikipedia.org/wiki/"),
                            (b"rm", b"rm.wikipedia.org/wiki/"),
                            (b"rmy", b"rmy.wikipedia.org/wiki/"),
                            (b"rn", b"rn.wikipedia.org/wiki/"),
                            (b"ro", b"ro.wikipedia.org/wiki/"),
                            (b"roa-rup", b"roa-rup.wikipedia.org/wiki/"),
                            (b"roa-tara", b"roa-tara.wikipedia.org/wiki/"),
                            (b"ru", b"ru.wikipedia.org/wiki/"),
                            (b"rue", b"rue.wikipedia.org/wiki/"),
                            (b"rw", b"rw.wikipedia.org/wiki/"),
                            (b"sa", b"sa.wikipedia.org/wiki/"),
                            (b"sah", b"sah.wikipedia.org/wiki/"),
                            (b"sc", b"sc.wikipedia.org/wiki/"),
                            (b"scn", b"scn.wikipedia.org/wiki/"),
                            (b"sco", b"sco.wikipedia.org/wiki/"),
                            (b"sd", b"sd.wikipedia.org/wiki/"),
                            (b"se", b"se.wikipedia.org/wiki/"),
                            (b"sg", b"sg.wikipedia.org/wiki/"),
                            (b"sh", b"sh.wikipedia.org/wiki/"),
                            (b"si", b"si.wikipedia.org/wiki/"),
                            (b"simple", b"simple.wikipedia.org/wiki/"),
                            (b"sk", b"sk.wikipedia.org/wiki/"),
                            (b"sl", b"sl.wikipedia.org/wiki/"),
                            (b"sm", b"sm.wikipedia.org/wiki/"),
                            (b"sn", b"sn.wikipedia.org/wiki/"),
                            (b"so", b"so.wikipedia.org/wiki/"),
                            (b"sq", b"sq.wikipedia.org/wiki/"),
                            (b"sr", b"sr.wikipedia.org/wiki/"),
                            (b"srn", b"srn.wikipedia.org/wiki/"),
                            (b"ss", b"ss.wikipedia.org/wiki/"),
                            (b"st", b"st.wikipedia.org/wiki/"),
                            (b"stq", b"stq.wikipedia.org/wiki/"),
                            (b"su", b"su.wikipedia.org/wiki/"),
                            (b"sv", b"sv.wikipedia.org/wiki/"),
                            (b"sw", b"sw.wikipedia.org/wiki/"),
                            (b"szl", b"szl.wikipedia.org/wiki/"),
                            (b"ta", b"ta.wikipedia.org/wiki/"),
                            (b"te", b"te.wikipedia.org/wiki/"),
                            (b"tet", b"tet.wikipedia.org/wiki/"),
                            (b"tg", b"tg.wikipedia.org/wiki/"),
                            (b"th", b"th.wikipedia.org/wiki/"),
                            (b"ti", b"ti.wikipedia.org/wiki/"),
                            (b"tk", b"tk.wikipedia.org/wiki/"),
                            (b"tl", b"tl.wikipedia.org/wiki/"),
                            (b"tn", b"tn.wikipedia.org/wiki/"),
                            (b"to", b"to.wikipedia.org/wiki/"),
                            (b"tpi", b"tpi.wikipedia.org/wiki/"),
                            (b"tr", b"tr.wikipedia.org/wiki/"),
                            (b"ts", b"ts.wikipedia.org/wiki/"),
                            (b"tt", b"tt.wikipedia.org/wiki/"),
                            (b"tum", b"tum.wikipedia.org/wiki/"),
                            (b"tw", b"tw.wikipedia.org/wiki/"),
                            (b"ty", b"ty.wikipedia.org/wiki/"),
                            (b"tyv", b"tyv.wikipedia.org/wiki/"),
                            (b"udm", b"udm.wikipedia.org/wiki/"),
                            (b"ug", b"ug.wikipedia.org/wiki/"),
                            (b"uk", b"uk.wikipedia.org/wiki/"),
                            (b"ur", b"ur.wikipedia.org/wiki/"),
                            (b"uz", b"uz.wikipedia.org/wiki/"),
                            (b"ve", b"ve.wikipedia.org/wiki/"),
                            (b"vec", b"vec.wikipedia.org/wiki/"),
                            (b"vep", b"vep.wikipedia.org/wiki/"),
                            (b"vi", b"vi.wikipedia.org/wiki/"),
                            (b"vls", b"vls.wikipedia.org/wiki/"),
                            (b"vo", b"vo.wikipedia.org/wiki/"),
                            (b"wa", b"wa.wikipedia.org/wiki/"),
                            (b"war", b"war.wikipedia.org/wiki/"),
                            (b"wo", b"wo.wikipedia.org/wiki/"),
                            (b"wuu", b"wuu.wikipedia.org/wiki/"),
                            (b"xal", b"xal.wikipedia.org/wiki/"),
                            (b"xh", b"xh.wikipedia.org/wiki/"),
                            (b"xmf", b"xmf.wikipedia.org/wiki/"),
                            (b"yi", b"yi.wikipedia.org/wiki/"),
                            (b"yo", b"yo.wikipedia.org/wiki/"),
                            (b"za", b"za.wikipedia.org/wiki/"),
                            (b"zea", b"zea.wikipedia.org/wiki/"),
                            (b"zh", b"zh.wikipedia.org/wiki/"),
                            (b"zh-classical", b"zh-classical.wikipedia.org/wiki/"),
                            (b"zh-min-nan", b"zh-min-nan.wikipedia.org/wiki/"),
                            (b"zh-yue", b"zh-yue.wikipedia.org/wiki/"),
                            (b"zu", b"zu.wikipedia.org/wiki/"),
                        ],
                    ),
                ),
                (
                    "contributions",
                    models.TextField(
                        help_text="Wiki contributions, as entered by user"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email, as entered by user", max_length=75
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE
                    ),
                ),
            ],
            options={},
            bases=(models.Model,),
        )
    ]
