# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 13:51


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("users", "0026_create_restricted")]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="data_restricted")
    ]
