# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 13:04


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0027_remove_userprofile_data_restricted"),
        ("users", "0026_remove_editor_last_updated"),
    ]

    operations = []
