# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_merge_20180522_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lang',
            field=models.CharField(blank=True, choices=[('af', 'Afrikaans'), ('ar', '\u0627\u0644\u0639\u0631\u0628\u064a\u0629'), ('ast', 'asturianu'), ('az', 'az-latn'), ('be', '\u0431\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f'), ('bg', '\u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438'), ('bn', '\u09ac\u09be\u0982\u09b2\u09be'), ('br', 'brezhoneg'), ('bs', 'bosanski'), ('ca', 'catal\xe0'), ('cs', '\u010de\u0161tina'), ('cy', 'Cymraeg'), ('da', 'dansk'), ('de', 'Deutsch'), ('dsb', 'dolnoserbski'), ('el', '\u0395\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac'), ('en', 'English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'espa\xf1ol'), ('es-ni', 'espa\xf1ol nicarag\xfcense'), ('et', 'eesti'), ('eu', 'euskara'), ('fa', '\u0641\u0627\u0631\u0633\u06cc'), ('fi', 'suomi'), ('fr', 'fran\xe7ais'), ('fy', 'Frysk'), ('ga', 'Gaeilge'), ('gd', 'G\xe0idhlig'), ('gl', 'galego'), ('he', '\u05e2\u05d1\u05e8\u05d9\u05ea'), ('hi', '\u0939\u093f\u0928\u094d\u0926\u0940'), ('hr', 'hrvatski'), ('hsb', 'hornjoserbsce'), ('hu', 'magyar'), ('ia', 'interlingua'), ('id', 'Bahasa Indonesia'), ('io', 'Ido'), ('is', '\xedslenska'), ('it', 'italiano'), ('ja', '\u65e5\u672c\u8a9e'), ('ka', '\u10e5\u10d0\u10e0\u10d7\u10e3\u10da\u10d8'), ('kk', 'kk-cyrl'), ('km', '\u1797\u17b6\u179f\u17b6\u1781\u17d2\u1798\u17c2\u179a'), ('kn', '\u0c95\u0ca8\u0ccd\u0ca8\u0ca1'), ('ko', '\ud55c\uad6d\uc5b4'), ('lb', 'L\xebtzebuergesch'), ('lt', 'lietuvi\u0173'), ('lv', 'latvie\u0161u'), ('mk', '\u043c\u0430\u043a\u0435\u0434\u043e\u043d\u0441\u043a\u0438'), ('ml', '\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02'), ('mn', '\u043c\u043e\u043d\u0433\u043e\u043b'), ('mr', '\u092e\u0930\u093e\u0920\u0940'), ('my', '\u1019\u103c\u1014\u103a\u1019\u102c\u1018\u102c\u101e\u102c'), ('nb', 'norsk (bokm\xe5l)'), ('ne', '\u0928\u0947\u092a\u093e\u0932\u0940'), ('nl', 'Nederlands'), ('nn', 'norsk (nynorsk)'), ('os', '\u0418\u0440\u043e\u043d'), ('pa', 'pa-guru'), ('pl', 'polski'), ('pt', 'portugu\xeas'), ('pt-br', 'portugu\xeas do Brasil'), ('ro', 'rom\xe2n\u0103'), ('ru', '\u0440\u0443\u0441\u0441\u043a\u0438\u0439'), ('sk', 'sloven\u010dina'), ('sl', 'sloven\u0161\u010dina'), ('sq', 'shqip'), ('sr', 'sr-cyrl'), ('sr-latn', 'srpski'), ('sv', 'svenska'), ('sw', 'Kiswahili'), ('ta', '\u0ba4\u0bae\u0bbf\u0bb4\u0bcd'), ('te', '\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41'), ('th', '\u0e44\u0e17\u0e22'), ('tr', 'T\xfcrk\xe7e'), ('tt', '\u0442\u0430\u0442\u0430\u0440\u0447\u0430'), ('udm', '\u0443\u0434\u043c\u0443\u0440\u0442'), ('uk', '\u0443\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430'), ('ur', '\u0627\u0631\u062f\u0648'), ('vi', 'Ti\u1ebfng Vi\u1ec7t'), ('zh-hans', '\u4e2d\u6587\uff08\u7b80\u4f53\uff09'), ('zh-hant', '\u4e2d\u6587\uff08\u7e41\u9ad4\uff09')], help_text='Language', max_length=128, null=True),
        ),
    ]
