# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-13 18:31


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0029_auto_20180612_1453")]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="lang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ar", "\u0627\u0644\u0639\u0631\u0628\u064a\u0629"),
                    ("en", "English"),
                    ("fi", "suomi"),
                    ("fr", "fran\xe7ais"),
                ],
                help_text="Language",
                max_length=128,
                null=True,
            ),
        )
    ]
