# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-10 13:26


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0030_auto_20180713_1831")]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="lang",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ar", "\u0627\u0644\u0639\u0631\u0628\u064a\u0629"),
                    ("en", "English"),
                    ("fi", "suomi"),
                    ("fr", "fran\xe7ais"),
                    ("ko", "\ud55c\uad6d\uc5b4"),
                    (
                        "mk",
                        "\u043c\u0430\u043a\u0435\u0434\u043e\u043d\u0441\u043a\u0438",
                    ),
                    (
                        "my",
                        "\u1019\u103c\u1014\u103a\u1019\u102c\u1018\u102c\u101e\u102c",
                    ),
                    ("pt", "portugu\xeas"),
                    ("pt-br", "portugu\xeas do Brasil"),
                    ("sv", "svenska"),
                    ("tr", "T\xfcrk\xe7e"),
                    ("zh-hans", "\u4e2d\u6587\uff08\u7b80\u4f53\uff09"),
                    ("zh-hant", "\u4e2d\u6587\uff08\u7e41\u9ad4\uff09"),
                ],
                help_text="Language",
                max_length=128,
                null=True,
            ),
        )
    ]
