# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20180713_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tos_applying',
            field=models.BooleanField(default=False, help_text='I agree'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tos_data_retention',
            field=models.BooleanField(default=False, help_text='I agree'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tos_important_note',
            field=models.BooleanField(default=False, help_text='I agree'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tos_intro',
            field=models.BooleanField(default=False, help_text='I agree'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tos_publisher_resources',
            field=models.BooleanField(default=False, help_text='I agree'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tos_requirements',
            field=models.BooleanField(default=False, help_text='I agree'),
        ),
    ]
