# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-20 16:39


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0037_auto_20190117_1008"),
    ]

    operations = [
        migrations.CreateModel(
            name="Authorization",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_authorized", models.DateField(auto_now_add=True)),
                (
                    "date_expires",
                    models.DateField(
                        blank=True,
                        help_text="The date this authorization expires.",
                        null=True,
                    ),
                ),
                (
                    "authorized_user",
                    models.ForeignKey(
                        help_text="The authorized user.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "authorizer",
                    models.ForeignKey(
                        help_text="The authorizing user.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "authorization",
                "verbose_name_plural": "authorizations",
            },
        ),
    ]
