# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-16 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='author',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
