# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-17 04:59


from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0046_auto_20191001_1455"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authorization", old_name="authorized_user", new_name="user"
        ),
    ]
