# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-16 17:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0048_reset_tou_for_all_users"),
    ]

    operations = []
