# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-28 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0051_auto_20200204_1710")]

    operations = [
        migrations.AddField(
            model_name="editor",
            name="ignore_wp_blocks",
            field=models.BooleanField(
                default=False,
                help_text="Ignore the 'not currently blocked' criterion for access?",
            ),
        )
    ]
