# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-08 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0053_twl_team_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(name="authorization", unique_together=set([])),
    ]
