# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-08 17:20
from __future__ import unicode_literals

from django.db import migrations


def partner_to_partners(apps, schema_editor):
    """
    Adds the Partner object in Authorization.partner to the
    many-to-many relationship in Authorization.partners
    """
    authorization_model = apps.get_model("users", "Authorization")

    for authorization in authorization_model.objects.all():
        authorization.partners.add(authorization.partner)


class Migration(migrations.Migration):

    dependencies = [("users", "0054_auto_20200508_1715")]

    operations = [migrations.RunPython(partner_to_partners)]
