# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-08 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0055_authorization_data_partners_foreignkey_to_manytomany")
    ]

    operations = [migrations.RemoveField(model_name="authorization", name="partner")]
