# Generated by Django 3.0.9 on 2020-08-04 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0059_auto_20200706_1659"),
    ]

    operations = []
