# Generated by Django 3.0.11 on 2021-02-01 14:42

from django.db import migrations, models
from django.conf import settings


def twl_team(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    User.objects.get_or_create(
        username="TWL Team", email="wikipedialibrary@wikimedia.org"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0067_remove_editor_editcounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="project_page_2021_notification_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(twl_team, migrations.RunPython.noop),
    ]
