# Generated by Django 3.0.13 on 2021-03-31 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0069_auto_20210215_1404"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="proxy_notification_sent",
        ),
    ]
