# Generated by Django 3.1.13 on 2021-09-28 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0078_editor_ignore_wp_bundle_eligible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="authorization",
            name="stream",
        ),
    ]
