# Generated by Django 3.2.11 on 2022-01-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0082_alter_userprofile_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="editor",
            name="wp_block_hash",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="A hash that is generated with a user's block data",
                max_length=255,
            ),
        ),
    ]
