# Generated by Django 3.2.12 on 2022-03-02 15:53

from django.db import migrations
from TWLight.users.helpers.authorizations import delete_duplicate_bundle_authorizations


def delete_duplicate_bundle_auths(apps, schema_editor):
    """
    Delete duplicate bundle auths using helper
    """
    authorization_model = apps.get_model("users", "Authorization")

    delete_duplicate_bundle_authorizations(authorization_model.objects.all())


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0084_alter_userprofile_lang"),
    ]

    operations = [migrations.RunPython(delete_duplicate_bundle_auths)]
