# Generated by Django 3.2.13 on 2022-05-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0086_alter_userprofile_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="my_library_cache_key",
            field=models.CharField(
                blank=True, editable=False, max_length=256, null=True
            ),
        ),
    ]
