# Generated by Django 3.2.18 on 2023-05-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0090_alter_userprofile_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="enable_suggestion_notification",
            field=models.BooleanField(
                default=True, help_text="Does this user want suggestion notifications?"
            ),
        ),
    ]
