# Generated by Django 4.2.11 on 2024-06-25 01:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0095_alter_userprofile_lang"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="editor",
            name="occupation",
        ),
    ]
