# Generated by Django 4.2.16 on 2024-11-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0101_alter_userprofile_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="editor",
            name="ignore_wp_account_age_requirement",
            field=models.BooleanField(
                default=False,
                help_text="Ignore account age criteria for bundle access?",
            ),
        ),
        migrations.AddField(
            model_name="editor",
            name="ignore_wp_edit_requirement",
            field=models.BooleanField(
                default=False, help_text="Ignore edit count criteria for bundle access?"
            ),
        ),
    ]
