# Generated by Django 4.2.24 on 2025-12-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0113_alter_userprofile_lang"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="survey_email_sent",
            field=models.BooleanField(
                default=False,
                help_text="Has this user recieved the most recent survey email?",
            ),
        ),
    ]
