# Generated by Django 3.1.13 on 2021-08-02 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial_squashed_0029_remove_application_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="requested_access_duration",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 month"),
                    (3, "3 months"),
                    (6, "6 months"),
                    (12, "12 months"),
                ],
                help_text="User selection of when they'd like their account to expire (in months). Required for proxied resources; optional otherwise.",
                null=True,
            ),
        ),
    ]
