# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'applications', '0020_auto_20180529_1256'), (b'applications', '0021_auto_20180529_1310'), (b'applications', '0022_auto_20180529_1312')]

    dependencies = [
        ('applications', '0019_application_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='users.Editor'),
        ),
        migrations.AlterField(
            model_name='application',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='users.Editor'),
        ),
        migrations.AlterField(
            model_name='application',
            name='sent_by',
            field=models.ForeignKey(blank=True, help_text='The user who sent this application to the partner', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
