# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_application_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
