# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-04 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_application_hidden'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='application',
            managers=[
                ('include_invalid', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Under discussion'), (2, 'Approved'), (3, 'Not approved'), (4, 'Sent to partner'), (5, 'Invalid')], default=0),
        ),
    ]
