# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-10 17:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_auto_20181209_1315'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='application',
            managers=[
                ('include_invalid', django.db.models.manager.Manager()),
            ],
        ),
    ]
