# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_auto_20190104_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='account_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
