# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_auto_20190329_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='proxy_account_length',
            field=models.IntegerField(blank=True, choices=[(1, b'1 month'), (3, b'3 months'), (6, b'6 months'), (12, b'12 months')], help_text="User selection of when they'd like their account to expire (in months). Only relevant if the applied partner/collection has authorization_method as 'proxy'.", null=True),
        ),
    ]
