# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("applications", "0024_application_requested_access_duration")]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="requested_access_duration",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (12, "12 months"),
                    (6, "6 months"),
                    (3, "3 months"),
                    (1, "1 month"),
                ],
                help_text="User selection of when they'd like their account to expire (in months). Required for proxied resources; optional otherwise.",
                null=True,
            ),
        )
    ]
