# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-05 21:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("applications", "0025_auto_20191030_0919")]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="specific_stream",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="resources.Stream",
            ),
        )
    ]
