# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-17 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("applications", "0026_auto_20200305_2144")]

    operations = [
        migrations.AddField(
            model_name="application",
            name="waitlist_status",
            field=models.BooleanField(default=False),
        )
    ]
