# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-28 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_application_waitlist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='waitlist_status',
            field=models.BooleanField(default=False, help_text='Mark as True if the partner is WAITLISTED'),
        ),
    ]
