# Generated by Django 3.0.11 on 2020-12-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0028_auto_20200428_1347"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="hidden",
        ),
    ]
