name: Coveralls Reporting Check

# Controls when the workflow will run
on:
  schedule:
      - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  coveralls_check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # Runs a single command using the runners shell
      - name: Coveralls reporting check
        run: "curl -f -s -o /dev/null -w '%{http_code}' https://coveralls.io/builds/$(git rev-parse HEAD).json || curl -f -s -o /dev/null -w '%{http_code}' https://coveralls.io/builds/$(git rev-parse HEAD~).json"
