# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-30 13:50


from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [("resources", "0042_auto_20180426_2025")]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="company_location",
            field=django_countries.fields.CountryField(
                help_text="Partner's primary location.", max_length=2, null=True
            ),
        )
    ]
