# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-31 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0043_partner_company_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='The coordinator for this Partner, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
