# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 12:53


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("resources", "0046_auto_20180612_1506")]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="coordinator",
            field=models.ForeignKey(
                blank=True,
                help_text="The coordinator for this Partner, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
