# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-03 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0048_auto_20180713_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='accounts_available',
            field=models.PositiveSmallIntegerField(default=0, help_text='Add number of new accounts to the existing value, not by reseting it to zero.'),
        ),
        migrations.AddField(
            model_name='stream',
            name='accounts_available',
            field=models.PositiveSmallIntegerField(default=0, help_text='Add number of new accounts to the existing value, not by reseting it to zero.'),
        ),
    ]
