# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 10:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0048_auto_20180713_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='excerpt_limit',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional excerpt limit in terms of number of words per article. Leave empty if no limit.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='excerpt_limit_percentage',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional excerpt limit in terms of percentage (%) of an article. Leave empty if no limit.', null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Not available'), (2, 'Waitlisted')], default=1, help_text='Should this Partner be displayed to users? Is it open for applications right now?'),
        ),
    ]
