# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0048_auto_20180713_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='additional_resources',
            field=models.TextField(blank=True, help_text='Optional help resources for this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='additional_resources_ar',
            field=models.TextField(blank=True, help_text='Optional help resources for this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='additional_resources_en',
            field=models.TextField(blank=True, help_text='Optional help resources for this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='additional_resources_fi',
            field=models.TextField(blank=True, help_text='Optional help resources for this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='additional_resources_fr',
            field=models.TextField(blank=True, help_text='Optional help resources for this partner.', null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='status',
            field=models.IntegerField(choices=[(0, 'Available'), (1, 'Not available'), (2, 'Waitlisted')], default=1, help_text='Should this Partner be displayed to users? Is it open for applications right now?'),
        ),
    ]
