# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0049_auto_20180810_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='additional_resources',
            field=models.TextField(blank=True, help_text='Optional help resources for this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='additional_resources_ar',
            field=models.TextField(blank=True, help_text='Optional help resources for this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='additional_resources_en',
            field=models.TextField(blank=True, help_text='Optional help resources for this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='additional_resources_fi',
            field=models.TextField(blank=True, help_text='Optional help resources for this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='additional_resources_fr',
            field=models.TextField(blank=True, help_text='Optional help resources for this partner.', null=True),
        ),
    ]
