# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 14:41


import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resources", "0049_auto_20180810_1059")]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="excerpt_limit",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Optional excerpt limit in terms of number of words per article. Leave empty if no limit.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="excerpt_limit_percentage",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Optional excerpt limit in terms of percentage (%) of an article. Leave empty if no limit.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
