# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0049_auto_20180810_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_company_name', models.CharField(help_text="Partner's name (e.g. McFarland). Note: this will be user-visible and *not translated*.", max_length=40)),
                ('description', models.TextField(blank=True, help_text="Optional description of this partner's resources.", max_length=1000)),
                ('company_url', models.URLField(blank=True, help_text='Link to terms of use. Required if users must agree to terms of use to get access; optional otherwise.', null=True)),
                ('expected_usage_level', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Low'), (2, 'Medium'), (3, 'High')], default=0, help_text='Should this Partner be displayed to users? Is it open for applications right now?')),
                ('plus_ones', models.ForeignKey(blank=True, help_text='The coordinator for this Partner, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['suggested_company_name'],
                'verbose_name': 'suggestion',
                'verbose_name_plural': 'suggestions',
            },
        ),
    ]
