# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0049_auto_20180810_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='description',
            new_name='short_description',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='description_ar',
            new_name='short_description_ar',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='description_en',
            new_name='short_description_en',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='description_fi',
            new_name='short_description_fi',
        ),
        migrations.RenameField(
            model_name='partner',
            old_name='description_fr',
            new_name='short_description_fr',
        ),
    ]
