# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0050_suggest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggest',
            name='expected_usage_level',
        ),
        migrations.AlterField(
            model_name='suggest',
            name='company_url',
            field=models.URLField(blank=True, help_text="Link to the potential partner's website.", null=True),
        ),
        migrations.AlterField(
            model_name='suggest',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of this potential partner.', max_length=1000),
        ),
        migrations.RemoveField(
            model_name='suggest',
            name='plus_ones',
        ),
        migrations.AddField(
            model_name='suggest',
            name='plus_ones',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='suggest',
            name='suggested_company_name',
            field=models.CharField(help_text="Potential partner's name (e.g. McFarland).", max_length=40),
        ),
    ]
