# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-15 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resources", "0050_auto_20180810_1441")]

    operations = [
        migrations.RenameField(
            model_name="partner", old_name="description", new_name="short_description"
        ),
        migrations.RenameField(
            model_name="partner",
            old_name="description_ar",
            new_name="short_description_ar",
        ),
        migrations.RenameField(
            model_name="partner",
            old_name="description_en",
            new_name="short_description_en",
        ),
        migrations.RenameField(
            model_name="partner",
            old_name="description_fi",
            new_name="short_description_fi",
        ),
        migrations.RenameField(
            model_name="partner",
            old_name="description_fr",
            new_name="short_description_fr",
        ),
        migrations.AddField(
            model_name="partner",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.",
                verbose_name=b"long description",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="description_ar",
            field=models.TextField(
                blank=True,
                help_text="Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.",
                null=True,
                verbose_name=b"long description",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="description_en",
            field=models.TextField(
                blank=True,
                help_text="Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.",
                null=True,
                verbose_name=b"long description",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="description_fi",
            field=models.TextField(
                blank=True,
                help_text="Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.",
                null=True,
                verbose_name=b"long description",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="description_fr",
            field=models.TextField(
                blank=True,
                help_text="Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.",
                null=True,
                verbose_name=b"long description",
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="short_description",
            field=models.TextField(
                blank=True,
                help_text="Optional short description of this partner's resources.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="short_description_ar",
            field=models.TextField(
                blank=True,
                help_text="Optional short description of this partner's resources.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="short_description_en",
            field=models.TextField(
                blank=True,
                help_text="Optional short description of this partner's resources.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="short_description_fi",
            field=models.TextField(
                blank=True,
                help_text="Optional short description of this partner's resources.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="partner",
            name="short_description_fr",
            field=models.TextField(
                blank=True,
                help_text="Optional short description of this partner's resources.",
                max_length=1000,
                null=True,
            ),
        ),
    ]
