# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-26 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_application_hidden'),
        ('resources', '0051_auto_20180815_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='An access code for this partner.', max_length=60)),
                ('application', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesscodes', to='applications.Application')),
            ],
            options={
                'verbose_name': 'access code',
                'verbose_name_plural': 'access codes',
            },
        ),
        migrations.RemoveField(
            model_name='partner',
            name='bundle',
        ),
        migrations.AddField(
            model_name='partner',
            name='distribution_type',
            field=models.IntegerField(choices=[(0, 'Email'), (1, 'Access codes'), (2, 'Proxy'), (3, 'Library Bundle')], default=0, help_text='Which distribution method does this partner use? Default to Email if unknown.'),
        ),
        migrations.AddField(
            model_name='accesscode',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesscodes', to='resources.Partner'),
        ),
    ]
