# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-30 15:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0051_auto_20180815_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_company_name', models.CharField(help_text="Potential partner's name (e.g. McFarland).", max_length=40)),
                ('description', models.TextField(blank=True, help_text='Optional description of this potential partner.', max_length=1000)),
                ('company_url', models.URLField(blank=True, help_text="Link to the potential partner's website.", null=True)),
                ('plus_ones', models.ManyToManyField(help_text='Users who support this suggestion.', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['suggested_company_name'],
                'verbose_name': 'suggestion',
                'verbose_name_plural': 'suggestions',
            },
        ),
    ]
