# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0052_auto_20180827_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='additional_resources',
            field=models.TextField(blank=True, help_text='Comma separated list of video tutorials (URLs).', verbose_name=b'video tutorials'),
        ),
        migrations.AddField(
            model_name='partner',
            name='additional_resources_ar',
            field=models.TextField(blank=True, help_text='Comma separated list of video tutorials (URLs).', null=True, verbose_name=b'video tutorials'),
        ),
        migrations.AddField(
            model_name='partner',
            name='additional_resources_en',
            field=models.TextField(blank=True, help_text='Comma separated list of video tutorials (URLs).', null=True, verbose_name=b'video tutorials'),
        ),
        migrations.AddField(
            model_name='partner',
            name='additional_resources_fi',
            field=models.TextField(blank=True, help_text='Comma separated list of video tutorials (URLs).', null=True, verbose_name=b'video tutorials'),
        ),
        migrations.AddField(
            model_name='partner',
            name='additional_resources_fr',
            field=models.TextField(blank=True, help_text='Comma separated list of video tutorials (URLs).', null=True, verbose_name=b'video tutorials'),
        ),
    ]
