# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 16:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0052_auto_20180827_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_company_name', models.CharField(help_text="Potential partner's name (e.g. McFarland).", max_length=40)),
                ('description', models.TextField(blank=True, help_text='Optional description of this potential partner.', max_length=1000)),
                ('company_url', models.URLField(blank=True, help_text="Link to the potential partner's website.", null=True)),
                ('author', models.ForeignKey(blank=True, help_text='User who authored this suggestion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestion_author', to=settings.AUTH_USER_MODEL)),
                ('upvoted_users', models.ManyToManyField(blank=True, help_text='Users who have upvoted this suggestion.', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['suggested_company_name'],
                'verbose_name': 'suggestion',
                'verbose_name_plural': 'suggestions',
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='description_ko',
            field=models.TextField(blank=True, help_text='Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.', null=True, verbose_name=b'long description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_mk',
            field=models.TextField(blank=True, help_text='Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.', null=True, verbose_name=b'long description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_my',
            field=models.TextField(blank=True, help_text='Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.', null=True, verbose_name=b'long description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_pt',
            field=models.TextField(blank=True, help_text='Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.', null=True, verbose_name=b'long description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text='Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.', null=True, verbose_name=b'long description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_sv',
            field=models.TextField(blank=True, help_text='Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.', null=True, verbose_name=b'long description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_tr',
            field=models.TextField(blank=True, help_text='Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.', null=True, verbose_name=b'long description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_zh_hans',
            field=models.TextField(blank=True, help_text='Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.', null=True, verbose_name=b'long description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description_zh_hant',
            field=models.TextField(blank=True, help_text='Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.', null=True, verbose_name=b'long description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='send_instructions_ko',
            field=models.TextField(blank=True, help_text='Optional instructions for sending application data to this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='send_instructions_mk',
            field=models.TextField(blank=True, help_text='Optional instructions for sending application data to this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='send_instructions_my',
            field=models.TextField(blank=True, help_text='Optional instructions for sending application data to this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='send_instructions_pt',
            field=models.TextField(blank=True, help_text='Optional instructions for sending application data to this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='send_instructions_pt_br',
            field=models.TextField(blank=True, help_text='Optional instructions for sending application data to this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='send_instructions_sv',
            field=models.TextField(blank=True, help_text='Optional instructions for sending application data to this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='send_instructions_tr',
            field=models.TextField(blank=True, help_text='Optional instructions for sending application data to this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='send_instructions_zh_hans',
            field=models.TextField(blank=True, help_text='Optional instructions for sending application data to this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='send_instructions_zh_hant',
            field=models.TextField(blank=True, help_text='Optional instructions for sending application data to this partner.', null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='short_description_ko',
            field=models.TextField(blank=True, help_text="Optional short description of this partner's resources.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='short_description_mk',
            field=models.TextField(blank=True, help_text="Optional short description of this partner's resources.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='short_description_my',
            field=models.TextField(blank=True, help_text="Optional short description of this partner's resources.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='short_description_pt',
            field=models.TextField(blank=True, help_text="Optional short description of this partner's resources.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='short_description_pt_br',
            field=models.TextField(blank=True, help_text="Optional short description of this partner's resources.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='short_description_sv',
            field=models.TextField(blank=True, help_text="Optional short description of this partner's resources.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='short_description_tr',
            field=models.TextField(blank=True, help_text="Optional short description of this partner's resources.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='short_description_zh_hans',
            field=models.TextField(blank=True, help_text="Optional short description of this partner's resources.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='short_description_zh_hant',
            field=models.TextField(blank=True, help_text="Optional short description of this partner's resources.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='description_ko',
            field=models.TextField(blank=True, help_text="Optional description of this stream's resources.", null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='description_mk',
            field=models.TextField(blank=True, help_text="Optional description of this stream's resources.", null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='description_my',
            field=models.TextField(blank=True, help_text="Optional description of this stream's resources.", null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='description_pt',
            field=models.TextField(blank=True, help_text="Optional description of this stream's resources.", null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='description_pt_br',
            field=models.TextField(blank=True, help_text="Optional description of this stream's resources.", null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='description_sv',
            field=models.TextField(blank=True, help_text="Optional description of this stream's resources.", null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='description_tr',
            field=models.TextField(blank=True, help_text="Optional description of this stream's resources.", null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='description_zh_hans',
            field=models.TextField(blank=True, help_text="Optional description of this stream's resources.", null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='description_zh_hant',
            field=models.TextField(blank=True, help_text="Optional description of this stream's resources.", null=True),
        ),
        migrations.AddField(
            model_name='textfieldtag',
            name='name_ko',
            field=models.TextField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='textfieldtag',
            name='name_mk',
            field=models.TextField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='textfieldtag',
            name='name_my',
            field=models.TextField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='textfieldtag',
            name='name_pt',
            field=models.TextField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='textfieldtag',
            name='name_pt_br',
            field=models.TextField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='textfieldtag',
            name='name_sv',
            field=models.TextField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='textfieldtag',
            name='name_tr',
            field=models.TextField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='textfieldtag',
            name='name_zh_hans',
            field=models.TextField(max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='textfieldtag',
            name='name_zh_hant',
            field=models.TextField(max_length=100, null=True, verbose_name='Name'),
        ),
    ]
