# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0052_auto_20180827_0824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_company_name', models.CharField(help_text="Potential partner's name (e.g. McFarland).", max_length=40)),
                ('description', models.TextField(blank=True, help_text='Optional description of this potential partner.', max_length=1000)),
                ('company_url', models.URLField(blank=True, help_text="Link to the potential partner's website.", null=True)),
                ('author', models.ForeignKey(blank=True, help_text='User who authored this suggestion.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggest_author', to=settings.AUTH_USER_MODEL)),
                ('plus_ones', models.ManyToManyField(blank=True, help_text='Users who support this suggestion.', related_name='suggest_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['suggested_company_name'],
                'verbose_name': 'suggestion',
                'verbose_name_plural': 'suggestions',
            },
        ),
    ]
