# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0052_accesscode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='bundle',
        ),
        migrations.AddField(
            model_name='partner',
            name='distribution_type',
            field=models.IntegerField(choices=[(0, 'Email'), (1, 'Access codes'), (2, 'Proxy'), (3, 'Library Bundle')], default=0, help_text='Which distribution method does this partner use? Default to Email if unknown.'),
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='editor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesscodes', to='users.Editor'),
        ),
    ]
