# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0053_auto_20180824_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesscodes', to='users.Editor'),
        ),
    ]
