# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_application_hidden'),
        ('resources', '0054_auto_20180824_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accesscode',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='accesscode',
            name='granted',
        ),
        migrations.AddField(
            model_name='accesscode',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesscodes', to='applications.Application'),
        ),
    ]
