# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-23 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0055_video'),
        ('resources', '0052_auto_20180926_1503'),
    ]

    operations = [
    ]
