# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-24 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0055_auto_20180824_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesscode',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accesscodes', to='applications.Application'),
        ),
    ]
