# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0061_auto_20190117_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='short_description_last_revision_ids',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
