# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-20 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0061_auto_20190117_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='An access code for this partner.', max_length=60)),
            ],
            options={
                'verbose_name': 'access code',
                'verbose_name_plural': 'access codes',
            },
        ),
        migrations.RemoveField(
            model_name='partner',
            name='bundle',
        ),
        migrations.AddField(
            model_name='partner',
            name='authorization_method',
            field=models.IntegerField(choices=[(0, 'Email'), (1, 'Access codes'), (2, 'Proxy'), (3, 'Library Bundle')], default=0, help_text="Which authorization method does this partner use? 'Email' means the accounts are set up via email, and is the default. Select 'Access Codes' if we send individual, or group, login details or access codes. 'Proxy' means access delivered directly via EZProxy, and Library Bundle is automated proxy-based access."),
        ),
    ]
