# Generated by Django 3.0.11 on 2021-02-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0063_auto_20190220_1639_squashed_0084_auto_20201019_1310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="date_created",
            field=models.DateField(auto_now_add=True),
        ),
    ]
