# Generated by Django 3.0.12 on 2021-02-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0064_auto_20210201_1612"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="description_he",
            field=models.TextField(
                blank=True,
                help_text="Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.",
                null=True,
                verbose_name="long description",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="send_instructions_he",
            field=models.TextField(
                blank=True,
                help_text="Optional instructions for sending application data to this partner.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="short_description_he",
            field=models.TextField(
                blank=True,
                help_text="Optional short description of this partner's resources.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="description_he",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this stream's resources.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="textfieldtag",
            name="name_he",
            field=models.TextField(max_length=100, null=True, verbose_name="Name"),
        ),
    ]
