# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0066_auto_20190507_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='accounts_available',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Add the number of new accounts to the existing value, not by resetting it to zero. If 'specific stream' is true, change accounts availability at the collection level.", null=True),
        ),
    ]
