# Generated by Django 3.1.8 on 2021-04-22 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0066_auto_20210420_1927"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="old_tags",
        ),
    ]
