# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0067_auto_20190509_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='proxy_account_length',
            field=models.BooleanField(default=False, help_text='Mark as true if the authorization method of this partner is proxy and requires the length of the account (expiry) be specified.'),
        ),
    ]
