# Generated by Django 3.1.8 on 2021-04-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0067_remove_partner_old_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="new_tags",
            field=models.JSONField(default=None, null=True),
        ),
    ]
