# Generated by Django 3.1.8 on 2021-05-08 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0070_auto_20210505_2158"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="tags",
        ),
        migrations.DeleteModel(
            name="TaggedTextField",
        ),
        migrations.DeleteModel(
            name="TextFieldTag",
        ),
    ]
