# Generated by Django 3.1.8 on 2021-05-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0071_remove_tags_field_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="description_lv",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this stream's resources.",
                null=True,
            ),
        ),
    ]
