# Generated by Django 3.1.8 on 2021-05-31 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0072_stream_description_lv"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="description_it",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this stream's resources.",
                null=True,
            ),
        ),
    ]
