# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-26 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resources", "0072_auto_20190808_1849")]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="accounts_available",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Add the number of new accounts to the existing value, not by resetting it to zero. If 'specific stream' is true, change accounts availability at the collection level.",
                null=True,
            ),
        )
    ]
