# Generated by Django 3.1.8 on 2021-06-01 16:29

import TWLight.resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0073_stream_description_it"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="description_as",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this stream's resources.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="description_bcl",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this stream's resources.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="description_dag",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this stream's resources.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="description_diq",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this stream's resources.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="description_mnw",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this stream's resources.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="description_ms",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this stream's resources.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="description_scn",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this stream's resources.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="description_sr_ec",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this stream's resources.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="language",
            field=models.CharField(
                choices=[
                    ("ar", "العربية"),
                    ("as", "অসমীয়া"),
                    ("bcl", "Bikol Central"),
                    ("br", "brezhoneg"),
                    ("da", "dansk"),
                    ("dag", "dagbanli"),
                    ("de", "Deutsch"),
                    ("diq", "Zazaki"),
                    ("en", "English"),
                    ("en-gb", "British English"),
                    ("eo", "Esperanto"),
                    ("es", "español"),
                    ("fa", "فارسی"),
                    ("fi", "suomi"),
                    ("fr", "français"),
                    ("he", "עברית"),
                    ("hi", "हिन्दी"),
                    ("id", "Bahasa Indonesia"),
                    ("it", "italiano"),
                    ("ja", "日本語"),
                    ("ko", "한국어"),
                    ("lv", "latviešu"),
                    ("mk", "македонски"),
                    ("mnw", "ဘာသာ မန်"),
                    ("mr", "मराठी"),
                    ("ms", "Bahasa Melayu"),
                    ("my", "မြန်မာဘာသာ"),
                    ("pl", "polski"),
                    ("pt", "português"),
                    ("pt-br", "português do Brasil"),
                    ("ro", "română"),
                    ("ru", "русский"),
                    ("scn", "sicilianu"),
                    ("sr-ec", "sr-cyrl"),
                    ("sv", "svenska"),
                    ("ta", "தமிழ்"),
                    ("tr", "Türkçe"),
                    ("uk", "українська"),
                    ("vi", "Tiếng Việt"),
                    ("zh-hans", "中文（简体）"),
                    ("zh-hant", "中文（繁體）"),
                ],
                max_length=8,
                unique=True,
                validators=[TWLight.resources.models.validate_language_code],
            ),
        ),
    ]
