# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-30 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resources", "0076_auto_20191011_0137")]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="requested_access_duration",
            field=models.BooleanField(
                default=False,
                help_text="Must be checked if the authorization method of this partner is proxy; optional otherwise.",
            ),
        )
    ]
