# Generated by Django 3.1.12 on 2021-06-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0077_auto_20210610_1739"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="description_guw",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this stream's resources.",
                null=True,
            ),
        ),
    ]
