# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-10 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resources", "0078_auto_20191119_2254")]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="company_name",
            field=models.CharField(
                help_text="Partner's name (e.g. McFarland). Note: this will be user-visible and *not translated*.",
                max_length=255,
            ),
        )
    ]
