# Generated by Django 3.1.13 on 2021-08-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0078_stream_description_guw"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="description_nl",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this stream's resources.",
                null=True,
            ),
        ),
    ]
