# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-12 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("resources", "0079_auto_20191210_1832")]

    operations = [
        migrations.AddField(
            model_name="textfieldtag",
            name="meta_url",
            field=models.URLField(
                blank=True,
                help_text="Link to Meta-Wiki (eg.: https://meta.wikimedia.org/wiki/The_Wikipedia_Library/Collections/Agroforestry) for additional information for this tag.",
                null=True,
            ),
        )
    ]
