# Generated by Django 3.1.13 on 2021-09-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0080_auto_20210907_1415"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="searchable",
            field=models.IntegerField(
                choices=[
                    (0, "Searchable"),
                    (1, "Not searchable"),
                    (2, "Partially searchable"),
                ],
                default=1,
                help_text="Indicates whether a partner is searchable in EDS or not.",
            ),
        ),
    ]
