# Generated by Django 3.0.10 on 2020-10-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0083_auto_20200804_1634"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="description_ind",
            field=models.TextField(
                blank=True,
                help_text="Optional detailed description in addition to the short description such as collections, instructions, notes, special requirements, alternate access options, unique features, citations notes.",
                null=True,
                verbose_name="long description",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="send_instructions_ind",
            field=models.TextField(
                blank=True,
                help_text="Optional instructions for sending application data to this partner.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="short_description_ind",
            field=models.TextField(
                blank=True,
                help_text="Optional short description of this partner's resources.",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="stream",
            name="description_ind",
            field=models.TextField(
                blank=True,
                help_text="Optional description of this stream's resources.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="textfieldtag",
            name="name_ind",
            field=models.TextField(max_length=100, null=True, verbose_name="Name"),
        ),
    ]
