# Generated by Django 3.2.19 on 2023-05-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0084_phabricatortask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suggestion",
            name="suggested_company_name",
            field=models.CharField(
                help_text="Potential partner's name (e.g. McFarland).", max_length=80
            ),
        ),
    ]
