# Generated by Django 4.2.11 on 2024-06-25 01:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0086_alter_partner_target_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="partner",
            name="occupation",
        ),
    ]
