# Generated by Django 4.2.19 on 2025-02-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "resources",
            "0075_auto_20210603_1500_squashed_0087_remove_partner_occupation",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="user_instructions",
            field=models.TextField(
                blank=True,
                help_text="Optional instructions for editors to use access codes or free signup URLs for this partner. Sent via email upon application approval (for links) or access code assignment.",
                null=True,
            ),
        ),
    ]
